export const GET_ASSETS_REQUEST = "GET_ASSETS_REQUEST"
export const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS"
export const GET_ASSETS_FAILURE = "GET_ASSETS_FAILURE"

export const GET_ASSET_BY_ID_REQUEST = "GET_ASSET_BY_ID_REQUEST"
export const GET_ASSET_BY_ID_SUCCESS = "GET_ASSET_BY_ID_SUCCESS"
export const GET_ASSET_BY_ID_FAILURE = "GET_ASSET_BY_ID_FAILURE"
